site_name: Discord-Bot-Demo docs
site_description: 'Documentation for Discord-Bot-Demo'
site_author: 'Cyber'
docs_dir: docs/
repo_url: 'https://github.com/Discord-Bot-Demo/discord-bot-demo.github.io'
nav:
    - index.md
    - usage.md
    - attributes.md
    - functions.md
theme:
  name: 'material'
  features:
    - navigation.sections
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css